_core:
  default_config_hash: yX1C7z3yMpNpdAc5eW9kGPZv9O3AXYmoX5S2-85glyE
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
linkedin_url: 'https://www.linkedin.com/company/zymphonies'
instagram_url: 'https://www.instagram.com/'
rss_url: rss.xml
show_social_icon: 1
show_credit_link: 1
show_slideshow: 1
slide_title_1: 'Hola, Soy Angélica'
slide_url_1: '#'
slide_image_path_1: /images/slider/slide_01.jpg
langcode: es
logo:
  use_default: 1
favicon:
  use_default: 1
slide_image_path1: {  }
